version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: "no"
    container_name: telemetrydb
    ports:
      - "3306:3306"
    networks: 
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=telemetry
      - MYSQL_USER=telemetryadmin
      - MYSQL_PASSWORD=admin123
networks:
  backend:
    name: backend